### ISSUE TITLE
http服务取得数据以可观察对象方式返回，处理完后不会刷新组件

### ISSUE THREAD

**Issue by winds2016** [greengerong/rebirth-ng#14]
需要手工方式刷新，能不能自动刷新，不用额外操作ChangeDetectorRef

**Comment by greengerong** [comment]
@winds2016  请问是哪一个组件，轻描述清晰一些。

**Comment by winds2016** [comment]
这不是组件的问题，只是我建议能不能在组件里解决，因为用primeng时就不用自己手动刷新。代码:
      this.httpService
        .getDatas()
        .subscribe(datas => {
           this.datas = Immutable.List(datas);         
           this.ChangeDetector.markForCheck();
        }, 
        error => {
          this.errorMessage = <any>error;
          this.ChangeDetector.markForCheck();
        }); 
this.datas是datatable的datasource，问题原因是在可观察对象中返回数据时对this.datas的修改不会自动刷新界面上的显示，包括在错误时对this.errorMessage的修改也不会自动显示在界面上（this.errorMessage没有绑定到组件上，直接显示），必须手工执行this.ChangeDetector.markForCheck();才刷新显示。

**Comment by greengerong** [comment]
相对于primeng，我们希望得到更好的性能，因为使用了onpush。你应该尝试去修改对象的input引用，而不是去`markForCheck `。

**Comment by winds2016** [comment]
也对，让我选择也是性能
修改对象的input引用，就是在变量前加上@input？
