### ISSUE TITLE
我在用reDatePicker时发现一个奇怪的问题

### ISSUE THREAD

**Issue by zxdmrg** [greengerong/rebirth-ng#19]
我在用reDatePicker时发现一个奇怪的问题。
`
<input class="ipt-time form-control" placeholder="" [showTimePicker]="true" [minDate]="minDate"
                       [maxDate]="maxDate" name="sendTimeKey1"
                       name="dp1" [(ngModel)]="formDataObj.formKey1.sendTime" reDatePicker
                       #datePickerkey1="datePicker" (click)="datePickerkey1.toggle($event)"
                       #sendTimeKey1="ngModel">
`
`
<input class="ipt-time form-control" placeholder="" [showTimePicker]="true" [minDate]="minDate"
                       [maxDate]="maxDate" name="sendTimeKey2"
                       name="dp2" [(ngModel)]="formDataObj.formKey2.sendTime" reDatePicker
                       #datePickerkey1="datePicker" (click)="datePickerkey2.toggle($event)"
                       #sendTimeKey2="ngModel">
`

初始的时候
formDataObj.formKey1.sendTime=‘2017-09-04 16:36’
formDataObj.formKey2.sendTime=‘2017-09-04 16:36’
然后我在某个事件发生的时候设置formDataObj.formKey1.sendTime=‘’
这时理论上界面应该只有第一个input框内容为空。但是实际上第二个input框也被清空了。但是这个清空只是单纯的数据看不见。保存的话或者断点formDataObj.formKey2.sendTime的值确实是正常存在的。

求解

我还尝试直接用dom操作第一个input元素让他的value='';但是发现只是看不见。数据也确实没清空，像没有实现双向绑定一样

**Comment by zxdmrg** [comment]
发现是我设置了两个name导致了这个bug。不过有谁知道其中的原理了

**Comment by greengerong** [comment]
你用了ngModel，设置FormControl时候肯定需要name，只能一个。
