### ISSUE TITLE
About Modal Dialog can auto close

### ISSUE THREAD

**Issue by zhangwei8387** [greengerong/rebirth-ng#20]
Dear Sir
    When I use the Modal Dialog Module,if I clicked the backdrop,the dialog would be closed automaticly.Can I change this setting to  not close the dialog automaticly? I did not find any option setting in ModalOptions.
  Pls give me some suggestions.Thank you very much.

**Comment by greengerong** [comment]
Yes. You can pass `modal:true` to modal:

export interface ModalOptions {
  component: Type<any>;
  componentFactoryResolver?: ComponentFactoryResolver;
  injector?: Injector;
  resolve?: any;
  backdrop?: boolean; 
  backdropClass?: string;
  keyboard?: boolean;
  modal?: boolean; // this option
  modalClass?: string;
  animation?: boolean;
  size?: 'lg' | 'sm';
  rootContainer?: ViewContainerRef;

}

**Comment by zhangwei8387** [comment]
Thank you very much.It works well.
