### ISSUE TITLE
Error: Should setup ViewContainerRef on modal options or rebirth config service!

### ISSUE THREAD

**Issue by ANGULAR-X** [greengerong/rebirth-ng#3]
按照demo例子使用Dialog出现报错：

` import {DialogService} from "ng2-rebirth-ui";`
 
```
confirm() {
    this.dialogService.confirm({
      title: '删除',
      content: 'This is <strong>rebirth alert</strong> content.',
      yes: '确定',
      no: '取消',
      html: true
    });
  }
```

Error: Should setup ViewContainerRef on modal options or rebirth config service!

**Comment by greengerong** [comment]
![image](https://cloud.githubusercontent.com/assets/2569893/24293710/1fecbfa8-10ce-11e7-9ea8-96cbb88807a4.png)

需要she设置container或者方法参数传递当前ViewContainerRef。

**Comment by greengerong** [comment]
@ANGULAR-X Can i close this question?

**Comment by ANGULAR-X** [comment]
@greengerong 如果把demo放在根组件app.component里面测试是可以的。如果将demo放在懒加载的RebirthModule注册的组件里面，则还是会同样的错误。

```
  {
    path:'rebirth',
    loadChildren:'./pages/rebirthui/rebirth.module#RebirthModule'
  },
```

**Comment by ANGULAR-X** [comment]
@greengerong 4.0在24号的时候正式发布的。你的包项目更新的比较快哦。我今天看的时候连包名都变了。

**Comment by greengerong** [comment]
你这种测试肯定是不对的。 RebirthModule是业务组件，你不该懒加载它。

而是 在你的APPModule注册 `RebirthModule.forRoot()` （注册全局服务），

以及在使用它的module依赖指令等module `RebirthModule`. 这是ng2 root module和feature module差距。

**Comment by ANGULAR-X** [comment]
@greengerong 我一直是把RebirthModule放在SharedModule里面。SharedModule则在APPModule里。我只是在懒加载模块中调用DialogService的方法。其他的步骤都是按照你demo上做的。

**Comment by greengerong** [comment]
你缺少了` RebirthModule.forRoot()` 注册root module。

这就像路由module， `RouterModule.forRoot`和`RouterModule.forChild`.

如果你不想用注册forRoot，这你需要在 方法参数中传入ViewContainerRef。


   this.dialogService.confirm({viewContainerRef: this.viewContainerRef ...};

**Comment by ANGULAR-X** [comment]
```
import {NgModule,ModuleWithProviders} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {RebirthNGModule} from "rebirth-ng";

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RebirthNGModule.forRoot(),
  ],
  declarations: [

  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RebirthNGModule
  ]
})

export class SharedModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: SharedModule,
      providers: []
    };
  }
}

```
这是我现在的SharedModule，这种方式会同样会报错。您说的第二种```
this.dialogService.confirm({viewContainerRef: this.viewContainerRef ...};


export interface DialogOptions {
    title: string;
    content: string;
    html?: boolean;
    yes?: string;
    no?: string;
    cssClass?: string;
}
```

这里面没有这个viewContainerRef属性~不知道是不是我哪里理解错误了？

**Comment by greengerong** [comment]
是的。忘记了在DialogService中，我并没放开viewContainerRef设置。如果你需要我可以在下个版本放开这个设置

**Comment by ANGULAR-X** [comment]
@greengerong 非常感谢！做项目时在选择组件库的时候在ng2-bootstrap和您这个库之间对比测试，现在用的是你这个库。

**Comment by greengerong** [comment]
@ANGULAR-X 我仍然建立你 注册 `RebirthModule.forRoot()`, 然后AppComponent设置rootContainer，这些使用更方便。我选择强制设置`rootContainer`,而不是直接用`document.body`是因为考虑服务端渲染等。

**Comment by greengerong** [comment]
@ANGULAR-X 刚发布了rebirth-ng@0.0.6，专门为你的需求开放了 ViewContainerRef接口，请更新。


	    export class DialogDemoComponent {

		  constructor(private dialogService: DialogService, private viewContainerRef: ViewContainerRef) {

		  }

		  confirm() {
		    this.dialogService.confirm({
		      title: 'I\'m a rebirth confirm!',
		      content: 'This is <strong>rebirth confirm</strong> content.',
		      html: true,
		      rootContainer: this.viewContainerRef  // Container
		    })
		      .subscribe(
		        data => console.log('Rebirth confirm get yes result:', data),
		        error => console.error('Rebirth confirm get no result:', error)
		      );
		  }
		}

**Comment by greengerong** [comment]
@ANGULAR-X 问题解决了？

**Comment by ANGULAR-X** [comment]
@greengerong 
```
    export class DialogDemoComponent {

	  constructor(private dialogService: DialogService, private viewContainerRef: ViewContainerRef) {

	  }

	  confirm() {
	    this.dialogService.confirm({
	      title: 'I\'m a rebirth confirm!',
	      content: 'This is <strong>rebirth confirm</strong> content.',
	      html: true,
	      rootContainer: this.viewContainerRef  // Container
	    })
	      .subscribe(
	        data => console.log('Rebirth confirm get yes result:', data),
	        error => console.error('Rebirth confirm get no result:', error)
	      );
	  }
	}
```
刚刚更新了包。这种方式可以了。

这是我现在的SharedModule及AppModule，在懒加载模块里面调用DialogService。注册 RebirthModule.forRoot()放在SharedModule里面却还是报之前的错。



```
import {NgModule,ModuleWithProviders} from '@angular/core';
import {CommonModule} from '@angular/common';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {RebirthNGModule} from "rebirth-ng";

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RebirthNGModule.forRoot(),
  ],
  declarations: [

  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RebirthNGModule
  ]
})

export class SharedModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: SharedModule,
      providers: []
    };
  }
}

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(ROUTES, {useHash: false}),
    SharedModule
  ],
  declarations: [
    AppComponent
  ],
  providers: [

  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```

**Comment by greengerong** [comment]
你的注册时有问题的的。 `AppModule`是`RebirthNGModule.forRoot()`; ShareModule才是`RebirthNGModule `. 这个注册和你这里写的 `RouterModule.forRoot`和`RouterModule.forChild`是一致的。 lazyload module会在继承父上下文同时新建module上下文，你这样是将它注入到你的lazyload module的上下文了。

或者你可以写一个在线demo演示。

**Comment by greengerong** [comment]
@ANGULAR-X  No response any, so close this question. You can reopen this question if you still have same question.

**Comment by ANGULAR-X** [comment]
@greengerong ok,thanks.
