### ISSUE TITLE
v6 项目启动报错 'rebirth-ng' module not found

### ISSUE THREAD

**Issue by shuihuasheng** [greengerong/rebirth-ng#30]
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app'
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app'
ERROR in ./src/app/demo/accordion/accordion-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/accordion'
ERROR in ./src/app/demo/action-button/action-button-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/action-button'
ERROR in ./src/app/demo/alert-box/alert-box-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/alert-box'
ERROR in ./src/app/demo/auto-complete/auto-complete-demo.mdoule.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/auto-complete'
ERROR in ./src/app/demo/badge/badge-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/badge'
ERROR in ./src/app/demo/breadcrumbs/breadcrumbs-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/breadcrumbs'
ERROR in ./src/app/demo/carousel/carousel-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/carousel'
ERROR in ./src/app/demo/checkbox-group/checkbox-group-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/checkbox-group'
ERROR in ./src/app/demo/data-table/data-table-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/data-table'
ERROR in ./src/app/demo/date-picker/date-picker-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/date-picker'
ERROR in ./src/app/demo/dialog/dialog-demo.component.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/dialog'
ERROR in ./src/app/demo/dialog/dialog-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/dialog'
ERROR in ./src/app/demo/draggable/draggable-demo.component.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/draggable'
ERROR in ./src/app/demo/draggable/draggable-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/draggable'
ERROR in ./src/app/demo/ellipsis/ellipsis-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/ellipsis'
ERROR in ./src/app/demo/file-upload/file-upload-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/file-upload'
ERROR in ./src/app/demo/flow-step/flow-step-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/flow-step'
ERROR in ./src/app/demo/image-upload/image-upload-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/image-upload'
ERROR in ./src/app/demo/infinite-scroll/infinite-scroll-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/infinite-scroll'
ERROR in ./src/app/demo/menu-bar/menu-bar-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/menu-bar'
ERROR in ./src/app/demo/modal/modal-demo.component.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/modal'
ERROR in ./src/app/demo/notify/notify-demo.component.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/notify'
ERROR in ./src/app/demo/notify/notify-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/notify'
ERROR in ./src/app/demo/overlay/overlay-demo.component.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/overlay'
ERROR in ./src/app/demo/pager/pager-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/pager'
ERROR in ./src/app/demo/pagination/pagination-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/pagination'
ERROR in ./src/app/demo/panel/panel-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/panel'
ERROR in ./src/app/demo/popover/popover-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/popover'
ERROR in ./src/app/demo/progress-bar/progress-bar-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/progress-bar'
ERROR in ./src/app/demo/radio-group/radio-group-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/radio-group'
ERROR in ./src/app/demo/rating/rating-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/rating'
ERROR in ./src/app/demo/select/select-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/select'
ERROR in ./src/app/demo/select-button/select-button-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/select-button'
ERROR in ./src/app/demo/slider/slider-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/slider'
ERROR in ./src/app/demo/switch/switch-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/switch'
ERROR in ./src/app/demo/tabs/tabs-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/tabs'
ERROR in ./src/app/demo/tabs/tabs-demo.component.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/tabs'
ERROR in ./src/app/demo/tags/tags-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/tags'
ERROR in ./src/app/demo/time-picker/time-picker-demo.component.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/time-picker'
ERROR in ./src/app/demo/time-picker/time-picker-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/time-picker'
ERROR in ./src/app/demo/tooltip/tooltip.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/tooltip'
ERROR in ./src/app/demo/tree-view/tree-view-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/tree-view'
ERROR in ./src/app/demo/validators/validators-demo.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/demo/validators'
ERROR in ./src/app/feature/show-case.component.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/feature'
ERROR in ./src/app/shared/shared.module.ts
Module not found: Error: Can't resolve '/Users/mc/program/self/js/angular-project/rebirth-ng/dist/rebirth-ng' in '/Users/mc/program/self/js/angular-project/rebirth-ng/src/app/shared'
ℹ ｢wdm｣: Failed to compile.
ERROR in src/app/app.component.ts(2,42): error TS2307: Cannot find module 'rebirth-ng'.
src/app/app.module.ts(47,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/app.module.ts(54,44): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/accordion/accordion-demo.component.ts(2,32): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/accordion/accordion-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/action-button/action-button-demo.component.ts(2,28): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/action-button/action-button-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/alert-box/alert-box-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/auto-complete/auto-complete-demo.mdoule.ts(6,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/badge/badge-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/breadcrumbs/breadcrumbs-demo.component.ts(2,28): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/breadcrumbs/breadcrumbs-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/carousel/carousel-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/checkbox-group/checkbox-group-demo.component.ts(2,40): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/checkbox-group/checkbox-group-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/data-table/data-table-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/date-picker/date-picker-demo.module.ts(6,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/dialog/dialog-demo.component.ts(2,31): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/dialog/dialog-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/draggable/draggable-demo.component.ts(2,36): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/draggable/draggable-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/ellipsis/ellipsis-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/file-upload/file-upload-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/flow-step/flow-step-demo.component.ts(2,26): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/flow-step/flow-step-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/image-upload/image-upload-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/infinite-scroll/infinite-scroll-demo.component.ts(2,41): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/infinite-scroll/infinite-scroll-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/menu-bar/menu-bar-demo.component.ts(2,25): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/menu-bar/menu-bar-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/modal/modal-demo.component.ts(2,37): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/notify/notify-demo.component.ts(2,44): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/notify/notify-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/overlay/overlay-demo.component.ts(2,32): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/pager/pager-demo.module.ts(5,29): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/pagination/pagination-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/panel/panel-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/popover/popover-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/progress-bar/progress-bar-demo.module.ts(6,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/radio-group/radio-group-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/rating/rating-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/select-button/select-button-demo.component.ts(2,34): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/select-button/select-button-demo.module.ts(6,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/select/select-demo.component.ts(2,29): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/select/select-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/slider/slider-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/switch/switch-demo.module.ts(6,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/tabs/tabs-demo.component.ts(2,31): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/tabs/tabs-demo.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/tags/tags-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/time-picker/time-picker-demo.component.ts(2,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/time-picker/time-picker-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/tooltip/tooltip.module.ts(5,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/tree-view/tree-view-demo.module.ts(4,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/demo/validators/validators-demo.module.ts(6,33): error TS2307: Cannot find module 'rebirth-ng'.
src/app/feature/show-case.component.ts(5,29): error TS2307: Cannot find module 'rebirth-ng'.
src/app/shared/shared.module.ts(8,33): error TS2307: Cannot find module 'rebirth-ng'.

**Comment by greengerong** [comment]
v6采用了angular/cli最新发布lib的方式。在运行npm start之前，需要运行 npm run build:lib
